In [1]:
## 모듈 로딩
import numpy as np

In [2]:
## ndarray 타입 데이터 생성

# 0으로 채워진 ndarray 객체 생성 => zeros()
np.zeros(2)

array([0., 0.])

In [3]:
np.zeros((2,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [10]:
# 1으로 채워진 ndarray 객체 생성 => ones()
np.ones(10), np.ones(10, dtype=int),np.ones((2, 5), dtype=np.bool_)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]))

In [13]:
# filled with a random number
np.random.randint(1, 15, (2, 5))

array([[ 9,  2,  3, 11,  8],
       [ 1,  9,  4, 11, 14]])

In [14]:
# 4) 0 <= x < 1
np.random.rand(2, 5)

array([[0.07494859, 0.60074272, 0.16797218, 0.73338017, 0.40844386],
       [0.52790882, 0.93757158, 0.52169612, 0.10819338, 0.15822341]])

In [15]:
# normal distribution
np.random.randn(2, 5)

array([[ 1.43327736,  2.6547994 , -1.21166587,  1.69268959, -1.14031579],
       [ 1.65688784,  1.31929701,  0.61136545, -0.441491  , -1.13908785]])

In [16]:
# 랜덤 고정
np.random.seed(4)

In [17]:
data = np.random.randn(10)
print(data)
np.random.shuffle(data)
print(data)

[ 0.05056171  0.49995133 -0.99590893  0.69359851 -0.41830152 -1.58457724
 -0.64770677  0.59857517  0.33225003 -1.14747663]
[ 0.69359851 -0.41830152  0.33225003  0.49995133  0.59857517 -1.58457724
 -0.99590893  0.05056171 -1.14747663 -0.64770677]


In [18]:
data.sum(),data.max(),data.argmax(),data.min(),data.argmin()

(-2.6190343310638076, 0.6935985082913116, 0, -1.5845772351121241, 5)