In [77]:
### 모듈로딩
from PIL import Image
from torchvision import transforms
from torchvision.datasets import ImageFolder

In [78]:
### 이미지 데이터 로딩
file = '../data/img/7e0133768625340913c220136a31fef2.jpg'

In [79]:
img = Image.open(file)

# img 속성 알아보기
img.format, img.height, img.width, img.mode, type(img)

('JPEG', 576, 1024, 'RGB', PIL.JpegImagePlugin.JpegImageFile)

In [90]:
# 사용법 => (1) 인스턴스 생성
to_tensor = transforms.ToTensor()

### (2) 인스턴스 변수 이용
imgTS = to_tensor(img)

### (3) 변환된 이미지 텐서 확인
imgTS.shape, imgTS.ndim, imgTS[0]

(torch.Size([3, 576, 1024]),
 3,
 tensor([[0.6784, 0.7216, 0.7647,  ..., 0.6784, 0.6627, 0.6078],
         [0.7529, 0.7961, 0.8353,  ..., 0.7333, 0.7176, 0.6667],
         [0.6706, 0.7255, 0.7725,  ..., 0.7529, 0.7373, 0.6863],
         ...,
         [0.4353, 0.4667, 0.4863,  ..., 0.0510, 0.0314, 0.0000],
         [0.4275, 0.4588, 0.4824,  ..., 0.0431, 0.0235, 0.0000],
         [0.3961, 0.4275, 0.4510,  ..., 0.0078, 0.0000, 0.0000]]))

In [92]:
### openCV
import cv2

img1 = cv2.imread(file)  # ndarray 반환 - BGR로 읽어옴
img2 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)  # 색상 채널 위치 RGB로 변환
img2.shape, img2.ndim, type(img2)

### 텐서화
imgTS2 = to_tensor(img1)
imgTS3 = to_tensor(img2)

imgTS2.shape, imgTS2.ndim, imgTS2[0], imgTS3[0]

(torch.Size([3, 576, 1024]),
 3,
 tensor([[0.3294, 0.3725, 0.4078,  ..., 0.2745, 0.2588, 0.2039],
         [0.4078, 0.4510, 0.4863,  ..., 0.3294, 0.3137, 0.2627],
         [0.3373, 0.3843, 0.4314,  ..., 0.3490, 0.3333, 0.2824],
         ...,
         [0.0745, 0.1059, 0.1255,  ..., 0.4784, 0.4588, 0.4275],
         [0.0667, 0.0980, 0.1216,  ..., 0.4706, 0.4510, 0.4196],
         [0.0353, 0.0667, 0.0902,  ..., 0.4353, 0.4196, 0.3882]]),
 tensor([[0.6784, 0.7216, 0.7569,  ..., 0.6784, 0.6627, 0.6078],
         [0.7529, 0.7961, 0.8314,  ..., 0.7333, 0.7176, 0.6667],
         [0.6784, 0.7255, 0.7725,  ..., 0.7529, 0.7373, 0.6863],
         ...,
         [0.4353, 0.4667, 0.4863,  ..., 0.0471, 0.0314, 0.0000],
         [0.4275, 0.4588, 0.4824,  ..., 0.0431, 0.0235, 0.0000],
         [0.3961, 0.4275, 0.4510,  ..., 0.0078, 0.0000, 0.0000]]))

In [93]:
preprocessing = transforms.Compose([

    transforms.Resize((28,28)),  # 사이즈가 작은 쪽에 맞춰서 조절
    transforms.ToTensor()
]) # 정규화는 무조건 마지막에 !!

In [94]:
preprocessing(img)

tensor([[[0.7412, 0.7922, 0.8196,  ..., 0.7373, 0.7373, 0.7373],
         [0.2000, 0.3294, 0.4980,  ..., 0.7412, 0.7333, 0.7216],
         [0.0275, 0.0275, 0.0353,  ..., 0.6549, 0.6000, 0.5294],
         ...,
         [0.4863, 0.4902, 0.4902,  ..., 0.0941, 0.4353, 0.1647],
         [0.4863, 0.4902, 0.4902,  ..., 0.0902, 0.4314, 0.1608],
         [0.4824, 0.4824, 0.4824,  ..., 0.0941, 0.4353, 0.1608]],

        [[0.4000, 0.4039, 0.4157,  ..., 0.3294, 0.3294, 0.3294],
         [0.4588, 0.4431, 0.4235,  ..., 0.3294, 0.3255, 0.3216],
         [0.4980, 0.5020, 0.4941,  ..., 0.2980, 0.2980, 0.3098],
         ...,
         [0.1804, 0.1804, 0.1804,  ..., 0.4549, 0.3412, 0.4392],
         [0.1804, 0.1804, 0.1804,  ..., 0.4157, 0.3373, 0.4431],
         [0.1843, 0.1843, 0.1843,  ..., 0.4000, 0.3333, 0.4431]],

        [[0.4196, 0.4235, 0.4353,  ..., 0.3333, 0.3333, 0.3333],
         [0.4431, 0.4314, 0.4235,  ..., 0.3373, 0.3333, 0.3255],
         [0.4667, 0.4667, 0.4667,  ..., 0.3059, 0.3059, 0.

### 이미지 데이터셋 <hr>
- torchvision.datasets 클래스 사용
    * 이미지 데이터 라벨링
    * 이미지 데이터 전처리

In [95]:
from torchvision.datasets import ImageFolder

In [96]:
img_root = '../data/img'
imgDS = ImageFolder(root = img_root, transform=preprocessing)

In [97]:
# 폴더명이 분류 클래스
# 폴더 이름  /     이름, 라벨        /  이미지 주소 
imgDS.classes, imgDS.class_to_idx, imgDS.imgs

(['symson'],
 {'symson': 0},
 [('../data/img\\symson\\3efd732efa099987ce7dd58d9626c26e.png', 0)])

In [98]:
from torch.utils.data import DataLoader

In [99]:
imgDL = DataLoader(imgDS)

In [100]:
for (feature, label) in imgDL:
    print(feature.shape, label.shape)
    break

torch.Size([1, 3, 28, 28]) torch.Size([1])
