### softmax(), sigmoid() 함수 <hr>
- sigmod() : y = wx + b 결과 1개를 전달 ===> 반환 : 0.0 ~ 1.0 사이 값으로 변환 => 이진분류(양성일 확률 구함)
- softmax() : y = wx + b 결과 여러 개를 전달 ===> 반환 : 여러개의 결과값의 합이 1.0이 되도록 변환 => 다중분류

In [4]:
# 모듈로딩
import torch                     # 파이토치 기본 모듈로 텐서 및 기본 함수들
import torch.nn.functional as F  # 파이토치 인공신경망 관련 함수들
import torch.optim as optim      #

In [6]:
# 임의의 데이터 생성
data1 = torch.tensor([1,2,1,1,2])
data1.shape

torch.Size([5])

In [7]:
F.sigmoid(data1) # 양성(1)일 확률 반환

tensor([0.7311, 0.8808, 0.7311, 0.7311, 0.8808])

In [22]:
data2 = data1.unsqueeze(dim = 0)
data2

tensor([[1, 2, 1, 1, 2]])

In [25]:
F.softmax(data2.float(), dim = 1)

tensor([[0.1185, 0.3222, 0.1185, 0.1185, 0.3222]])

In [27]:
input = torch.randn(2,3)
input

tensor([[ 0.3752, -0.0933, -1.0279],
        [-0.1889, -1.2705, -0.7497]])

In [39]:
output = F.softmax(input, dim = 1)
output, output.sum(dim = 1)

(tensor([[0.5343, 0.3344, 0.1313],
         [0.5236, 0.1775, 0.2989]]),
 tensor([1.0000, 1.0000]))

In [44]:
output.max(dim=1)[0], output.max(dim = 1)[1]  # 최댓값 , 인덱스

(tensor([0.5343, 0.5236]), tensor([0, 0]))

In [47]:
output.argmax(dim =1) # 인덱스만 반환

tensor([0, 0])