In [24]:
import torch
import torch.nn as nn
import torchviz
import torchinfo

In [2]:
class Net(nn.Module):
    
    # 모델 구성 요소 생성 및 구조 설정
    def __init__(self):
        super(Net, self).__init__()  # super() 도 가능
        
        self.fc1 = nn.Linear(8,4)
        self.fc2 = nn.Linear(4,2)
        self.fc3 = nn.Linear(2,1)
    
    # 순방향 학습 진행 함수
    def forward(self, x):
        return self.fc3(self.fc2(self.fc1(x)))

In [3]:
# 모델 인스턴스 생성
model = Net()

In [17]:
# 모델 인스턴스 속성 확인
# 모델의 특정 층 추출

model.fc1.weight, model.fc2.bias

(Parameter containing:
 tensor([[ 0.2768,  0.2550, -0.3042,  0.2248, -0.2919, -0.0987,  0.1787,  0.2176],
         [-0.1841, -0.1818, -0.0300, -0.0519, -0.1700, -0.3531,  0.0561,  0.2545],
         [ 0.0353, -0.1508, -0.3022, -0.2265,  0.0471,  0.0219, -0.1590,  0.2400],
         [-0.0057,  0.2374, -0.0025,  0.2634,  0.1425, -0.0537,  0.2990,  0.1807]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.4993, -0.4056], requires_grad=True))

In [11]:
# 모델의 각 층별 W, b 테넛 정보 확인
for i in model.parameters():  # 반환값이 Iterator(Generator)라면 반복문을 통하여 빼내야함
    print(i, end = '\n-------------------------------------------------------------------\n')

Parameter containing:
tensor([[ 0.2768,  0.2550, -0.3042,  0.2248, -0.2919, -0.0987,  0.1787,  0.2176],
        [-0.1841, -0.1818, -0.0300, -0.0519, -0.1700, -0.3531,  0.0561,  0.2545],
        [ 0.0353, -0.1508, -0.3022, -0.2265,  0.0471,  0.0219, -0.1590,  0.2400],
        [-0.0057,  0.2374, -0.0025,  0.2634,  0.1425, -0.0537,  0.2990,  0.1807]],
       requires_grad=True)
-------------------------------------------------------------------
Parameter containing:
tensor([ 0.2748,  0.3334, -0.2432,  0.3534], requires_grad=True)
-------------------------------------------------------------------
Parameter containing:
tensor([[-0.4419, -0.0475,  0.3821, -0.4654],
        [-0.2889, -0.3597,  0.4560,  0.0858]], requires_grad=True)
-------------------------------------------------------------------
Parameter containing:
tensor([-0.4993, -0.4056], requires_grad=True)
-------------------------------------------------------------------
Parameter containing:
tensor([[-0.5562, -0.0900]], requires

In [12]:
# 각 층의 이름도 같이 확인
for i in model.named_parameters(): 
    print(i, end = '\n-------------------------------------------------------------------\n')

('fc1.weight', Parameter containing:
tensor([[ 0.2768,  0.2550, -0.3042,  0.2248, -0.2919, -0.0987,  0.1787,  0.2176],
        [-0.1841, -0.1818, -0.0300, -0.0519, -0.1700, -0.3531,  0.0561,  0.2545],
        [ 0.0353, -0.1508, -0.3022, -0.2265,  0.0471,  0.0219, -0.1590,  0.2400],
        [-0.0057,  0.2374, -0.0025,  0.2634,  0.1425, -0.0537,  0.2990,  0.1807]],
       requires_grad=True))
-------------------------------------------------------------------
('fc1.bias', Parameter containing:
tensor([ 0.2748,  0.3334, -0.2432,  0.3534], requires_grad=True))
-------------------------------------------------------------------
('fc2.weight', Parameter containing:
tensor([[-0.4419, -0.0475,  0.3821, -0.4654],
        [-0.2889, -0.3597,  0.4560,  0.0858]], requires_grad=True))
-------------------------------------------------------------------
('fc2.bias', Parameter containing:
tensor([-0.4993, -0.4056], requires_grad=True))
-------------------------------------------------------------------

In [23]:
# 모델 구성 모든 Layer 가져오기
for i in model.children(): 
    print(i,end = '\n\n')

for i in model.named_children():
    print(i, end='\n\n')

Linear(in_features=8, out_features=4, bias=True)

Linear(in_features=4, out_features=2, bias=True)

Linear(in_features=2, out_features=1, bias=True)

('fc1', Linear(in_features=8, out_features=4, bias=True))

('fc2', Linear(in_features=4, out_features=2, bias=True))

('fc3', Linear(in_features=2, out_features=1, bias=True))


- Layer의 가중치 설정

In [20]:
# 세비어 알고리즘의 가중치 초기화
nn.init.xavier_uniform_(model.fc1.weight)

Parameter containing:
tensor([[-0.0647,  0.2881, -0.0966,  0.4701,  0.3082, -0.3806, -0.6365,  0.6621],
        [ 0.6676, -0.6655, -0.5578, -0.1223, -0.4713,  0.5800,  0.4575,  0.3725],
        [ 0.1367,  0.4506,  0.1445, -0.5266, -0.0349,  0.0756,  0.4949,  0.2000],
        [ 0.0799,  0.4868,  0.3865,  0.6178, -0.1759, -0.4114, -0.3383, -0.4532]],
       requires_grad=True)

In [21]:
# 헤 알고리즘의 가중치 초기화
nn.init.kaiming_uniform_(model.fc2.weight)


Parameter containing:
tensor([[ 7.1323e-04, -4.9638e-01, -8.3367e-02,  6.2773e-01],
        [ 2.8538e-01,  4.2043e-01,  2.4183e-01, -1.0030e+00]],
       requires_grad=True)

In [25]:
# torchinfo로 모델 구조 확인
from torchinfo import summary

summary(model, input_size=(1, 8))  # Param은 절편 갯수 포함

Layer (type:depth-idx)                   Output Shape              Param #
Net                                      [1, 1]                    --
├─Linear: 1-1                            [1, 4]                    36
├─Linear: 1-2                            [1, 2]                    10
├─Linear: 1-3                            [1, 1]                    3
Total params: 49
Trainable params: 49
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00