### 텐서(Tensor) 살펴보기
- Pytorch에서 데이터 저장 자료형
- 모델 입력(input), 출력(output) 데이터 형태

- 모듈 로딩

In [9]:
import torch

- Tensor 속성 관련 함수

In [17]:
# 매개변수 : 텐서 인스턴스, 텐서 변수명
def print_attribute(tensor, name):
    print(f'[ Tensor {name} Attribute ]')
    print(f' - tensor.shape : {tensor.shape}')
    print(f' - tensor.ndim : {tensor.ndim}D')
    print(f' - tensor dtype : {tensor.dtype}')
    print(f' - tensor.device : {tensor.device}')
    print(f' - tensor.requires_grad : {tensor.requires_grad}')
    print(f' - tensor.data : \n{tensor.data}')

- Tensor 생성 (1) 특정 데이터 타입의 텐서 생성
    * 타입별 텐서 클래스 생성자 활용
    * 예) IntTensor(), FloatTensor(), BoolTensor()

In [25]:
# 정수 타입 텐서 생성
t1 = torch.IntTensor(10)  # scalar 데이터 - 0차원
t2 = torch.IntTensor([10.,20.])  # 1차원 # 자동으로 형변환해주나, 데이터 손실이 일어나기 때문에 경고
t3 = torch.BoolTensor([1,1,0,-1])
t4 = torch.FloatTensor([10,20]) # 자동으로 형변환해서 객체 생성

C:\Users\kdp\AppData\Local\Temp\ipykernel_2900\807630545.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t2 = torch.IntTensor([10.,20.])  # 1차원 # 자동으로 형변환해주나, 데이터 손실이 일어나기 때문에 경고


In [26]:
print_attribute(t1,'t1')
print_attribute(t2,'t2')
print_attribute(t3,'t3') # 0만 False고 나머지 True
print_attribute(t4,'t4')

[ Tensor t1 Attribute ]
 - tensor.shape : torch.Size([10])
 - tensor.ndim : 1D
 - tensor dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
[ Tensor t2 Attribute ]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1D
 - tensor dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([10, 20], dtype=torch.int32)
[ Tensor t3 Attribute ]
 - tensor.shape : torch.Size([4])
 - tensor.ndim : 1D
 - tensor dtype : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([ True,  True, False,  True])
[ Tensor t4 Attribute ]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1D
 - tensor dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([10., 20.])


- Tensor 생성 (2) 원하는 값으로 텐서 생성 => torch.tensor()

In [34]:
# dtype 매개변수 : 원하는 데이터 타입 지정 가능
t1 = torch.tensor(10. , dtype = torch.bool)  # float32 -> bool
print_attribute(t1,'t1')

[ Tensor t1 Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor dtype : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
True


In [31]:
t2 = torch.tensor([1,2,3], dtype=torch.int8)  # 1D 데이터
print_attribute(t2,'t2')

[ Tensor t2 Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
10.0


In [36]:
t3 = torch.tensor([[1,2,3]], dtype=torch.int8)  # 2D 데이터
print_attribute(t3,'t3')

[ Tensor t3 Attribute ]
 - tensor.shape : torch.Size([1, 3])
 - tensor.ndim : 2D
 - tensor dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([[1, 2, 3]], dtype=torch.int8)


- Tensor 생성 (3) 특정 값으로 채운 텐서 => 0,1 등의 값

In [41]:
# 0으로 채운 텐서
t1 = torch.zeros(5,5, dtype=torch.int8) # 5행 5열 # 정수로 형변환 - 기본은 실수형
print_attribute(t1,'t1')

[ Tensor t1 Attribute ]
 - tensor.shape : torch.Size([5, 5])
 - tensor.ndim : 2D
 - tensor dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int8)


In [44]:
# 1으로 채운 텐서
t2 = torch.ones(2,4, dtype=torch.int8) # 2행 4열
print_attribute(t2,'t2')

[ Tensor t2 Attribute ]
 - tensor.shape : torch.Size([2, 4])
 - tensor.ndim : 2D
 - tensor dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int8)


In [46]:
# 이미 존재하는 텐서와 동일한 shape으로 잡고 값 채우기 => zeros_like(), ones_like()
# like가 들어간 메서드는 보통 shape를 복사하는 메서드
img = torch.tensor([[2,3,4,5,6,7],[2,3,4,5,6,7]])
print(img.shape)

torch.Size([2, 6])


In [50]:
zero_img = torch.zeros_like(img)
print(zero_img)

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])


In [52]:
one_img = torch.ones_like(img)
print(one_img)

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])


In [54]:
full_img = torch.full_like(img,7)
print(full_img)

tensor([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]])


In [56]:
# 대각선 방향으로 1 채우기
t1 = torch.eye(5)
print_attribute(t1,'t1')

[ Tensor t1 Attribute ]
 - tensor.shape : torch.Size([5, 5])
 - tensor.ndim : 2D
 - tensor dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


- Tensor 생성 방법 (4) : 임의의 값으로 Tensor 생성 => torch.rand(), torch.randn(), torch.randint()

In [60]:
t1 = torch.manual_seed(12) # 랜덤 초기값 설정

In [63]:
t5 = torch.rand( 2, 3 ) # [0, 1) 분포 안에서 랜덤 생성 # 2행 3열
print_attribute(t5,'t5')

[ Tensor t5 Attribute ]
 - tensor.shape : torch.Size([2, 3])
 - tensor.ndim : 2D
 - tensor dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([[0.4339, 0.8813, 0.3216],
        [0.2604, 0.2566, 0.1872]])


In [64]:
t6 = torch.randn( 2, 3) # standard normal 분포에서 랜덤생성 # 2행 3열
print_attribute(t6,'t6')

[ Tensor t6 Attribute ]
 - tensor.shape : torch.Size([2, 3])
 - tensor.ndim : 2D
 - tensor dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([[ 0.3641,  0.4331,  0.5895],
        [-1.2568,  0.4411, -0.2782]])


In [66]:
t7 = torch.randint( low=1, high=10, size=(2,3) ) # [low, high) low<= 값 < high
print_attribute(t7,'t7')

[ Tensor t7 Attribute ]
 - tensor.shape : torch.Size([2, 3])
 - tensor.ndim : 2D
 - tensor dtype : torch.int64
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data : 
tensor([[6, 1, 4],
        [3, 2, 4]])


- Tensor 생성 방법 (5) : Ndarray 객체 활용 => torch.from_numpy(), torch.as_tensor(), torch()

In [68]:
# 데이터 생성
import numpy as np

data = np.array([11, 22, 33])
print(data, data.dtype)

[11 22 33] int32


In [70]:
t1 = torch.from_numpy(data)
t2 = torch.as_tensor(data)
t3 = torch.tensor(data)

for i in [t1, t2, t3]:
    print(i)

tensor([11, 22, 33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)


In [71]:
# ndarray 원소 변경
data[0] = 100

In [73]:
# from_numpy(), as_tensor() => 데이터 공유
# tensor() => 복사본 생성 / 별개 : 데이터 공유 X
print(data,t1,t2,t3,sep='\n')

[100  22  33]
tensor([100,  22,  33], dtype=torch.int32)
tensor([100,  22,  33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)


In [74]:
# 범위를 가지고 Tensor를 채울때 사용
# 시작 <= ~ <=끝 범위 : 1간격 또는 지정된 간격의 요소 생성

t3 = torch.arange ( 2 ) # 0<= ~ < 2 1간격
t4 = torch.arange ( 1, 10 ) # 1<= ~ < 10 1간격
t5 = torch.arange ( 1, 10, 3 ) # 1<= ~ < 10 3간격