### Tensor 원소/요소 접근
- 인덱싱과 슬라이싱

In [1]:
# 모듈 로딩
import torch

In [3]:
# 텐서 생성
points = torch.tensor([[4.,2.],[5.,3.],[6.,4.]], dtype=torch.int16)
points

C:\Users\kdp\AppData\Local\Temp\ipykernel_14792\1738106437.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  points = torch.tensor([[4.,2.],[5.,3.],[6.,4.]], dtype=torch.int16)


tensor([[4, 2],
        [5, 3],
        [6, 4]], dtype=torch.int16)

In [9]:
# 텐서의 원소 1개 접근
# 데이터 3 추출
print(points[1][1])

# 데이터 4 추출(마지막 4)
print(points[2][1]) # points[-1][-1]

tensor(3, dtype=torch.int16)
tensor(4, dtype=torch.int16)


In [10]:
# 1번 행부터 나머지 모든 행 추출
print(points[1:])

tensor([[5, 3],
        [6, 4]], dtype=torch.int16)


- 브로드캐스팅 연산

In [12]:
#
m1 = torch.FloatTensor([[1, 2]]) # 1행 2열의 2차원
m2 = torch.FloatTensor([3]) # 1차원
m3 = m1 + m2

print(m3, m3.shape)

tensor([[4., 5.]]) torch.Size([1, 2])


In [16]:
m1 = torch.FloatTensor([[1, 2]]) # 1행 2열의 2차원
m2 = torch.FloatTensor([[3], [4]]) # 2행 1열의 2차원
m3 = m1 + m2 
# m1 : 1 2  m2 : 3 3   => 브로드 캐스팅
#      1 2       4 4
print(m1)
print(m2)
print(m3, m3.shape)

tensor([[1., 2.]])
tensor([[3.],
        [4.]])
tensor([[4., 5.],
        [5., 6.]]) torch.Size([2, 2])


In [21]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)

print( m1 * m2 )
print( m1.mul( m2 ) )

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [23]:
# 원소 단위 연산 수행 메서드들
m1.add(m2),m1.sub(m2),m1.mul(m2),m1.div(m2)

(tensor([[2., 3.],
         [5., 6.]]),
 tensor([[0., 1.],
         [1., 2.]]),
 tensor([[1., 2.],
         [6., 8.]]),
 tensor([[1.0000, 2.0000],
         [1.5000, 2.0000]]))

In [20]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)

m12= m1.matmul( m2 )
print( m12.shape)

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
torch.Size([2, 1])
