### 텐서 연결 & 결합

In [1]:
# 모듈 로딩
import torch

In [45]:
# 텐서 데이터 생성
torch.manual_seed(12) # 랜덤 초기값 설정
# 임의의 0. <= ~ <= 1. 실수
x = torch.rand(2,10)  # 2행 10열
# 임의의 정수 : low <= ~ <= high
y = torch.randint(0,2,(10,)) # 1차원
y2 = torch.randint(0,2,(2,10)) # 2행 10열

In [46]:
print(x.shape, x.ndim,sep = '\n')
print(y.shape, y.ndim, sep = '\n')
print(y2.shape, y2.ndim, sep = '\n')

torch.Size([2, 10])
2
torch.Size([10])
1
torch.Size([2, 10])
2


In [57]:
# tensor 연결 cat([텐서1, 텐서2....])
xy1 = torch.cat([x,y2], dim = 1)

In [65]:
# 집계함수는 aixs나 dim  기준이 반대

torch.return_types.max(
values=tensor([0.4657, 0.6948, 0.5830, 0.6318, 0.5559, 0.1272, 0.9790, 0.8443, 0.7312,
        0.7224, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000,
        0.0000, 0.0000]),
indices=tensor([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]))

In [61]:
# 행 단위로 최대값 및 최대값의 인덱스
max_value = xy1.max(dim =1)[0]
max_idx = xy1.max(dim =1)[1]

max_value, max_idx

tensor([1., 1.]) tensor([10, 12])


In [60]:
# 열 단위로 최대값 및 최대값의 인덱스 # dim = 0 or -1
max_value = xy1.max(dim =0)[0]
max_idx = xy1.max(dim =0)[1]

max_value, max_idx

(tensor([0.4657, 0.6948, 0.5830, 0.6318, 0.5559, 0.1272, 0.9790, 0.8443, 0.7312,
         0.7224, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000]),
 tensor([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]))