### Tensor shape 변경
- reshape(), view() : 원소 갯수가 유지됨! 기존 텐서 공유함

In [105]:
# 모듈 로딩
import torch

In [106]:
# 텐서 데이터 생성
t1 = torch.tensor([[1,2,3],[4,5,6]])
print(t1.shape, t1.ndim)
print(t1)

torch.Size([2, 3]) 2
tensor([[1, 2, 3],
        [4, 5, 6]])


In [107]:
# [2, 3] -> [3, 2] 형태 변경 : 원소 동일 6개
t1.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [108]:
# [2, 3] -> [6, 1] 형태 변경 : 원소 동일 6개
# -1 : 원소 수를 알아서 할당하라는 뜻
t1.view(6,1)
t1.view(-1,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [109]:
t1.view(-1,1) # n행 1열로 만들어줘
t1.view(1,-1) # 1행 n열로 만들어줘

tensor([[1, 2, 3, 4, 5, 6]])

In [110]:
# tensor.reshape() - view보다 reshape 쓰기를 권장
t1.reshape(-1,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [111]:
# 원소 수 유지되어야 함 !
# t1.shape(-1,7) - 원소 수가 6갠데 필요한 최소한의 원소 수가 7개이므로 부족함

- 전치 : 열 <-> 형 변경

In [112]:
print(t1.shape)

t2 = t1.T
print(t2.shape, t2.is_contiguous()) # t2가 연속되어있는지 확인하는 메서드

torch.Size([2, 3])
torch.Size([3, 2]) False


In [113]:
# t2.view(-1,6) => Error

In [114]:
t3 = t2.reshape(-1,6) # 전치하면 복사본 생성함 -> 원본에 공유안됨 주의 !!
print(t3,t3.is_contiguous())

tensor([[1, 4, 2, 5, 3, 6]]) True


### 텐서 데이터의 메모리 저장 정보 즉 메타데이터
- 현재 저장 형태, 검색 방향 정보, 시작 정보

In [115]:
# 텐서 데이터 생성
t1 = torch.tensor([[1,2,3],[4,5,6]])
print(t1.storage()) # 메모리에 어떤 순서로 저장되어 있는지 확인
print(t1.storage_offset()) # 시작지점
print(t1.stride()) # 행(row) 사이의 간격과 열(column) 사이의 간격 반환
print(t1.is_contiguous()) # 데이터가 연속적으로 들어가있는지 확인

 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
0
(3, 1)
True


In [116]:
t2 = t1.view(-1,2)
print(t2.storage()) # 메모리에 어떤 순서로 저장되어 있는지 확인
print(t2.storage_offset()) # 시작지점
print(t2.stride()) # 행(row) 사이의 간격과 열(column) 사이의 간격 반환
print(t2.is_contiguous()) # 데이터가 연속적으로 들어가있는지 확인

 1
 2
 3
 4
 5
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
0
(2, 1)
True


### 차원 제거 / 추가
- tensor.squeeze() : 텐서에서 차원이 1인 것 제거
- tensor.unsqueeze(dim) : 텐서에서 차원이 1인 것 추가

In [117]:
# 데이터 생성
t1 = torch.tensor([[1,2],[4,5]])
t2 = torch.tensor([[1,2,3,4]])
t3 = torch.tensor([[[1,2,3,4]]]) # 3차원

In [118]:
print(t1.shape, t1.ndim)
print(t2.shape, t2.ndim)
print(t3.shape, t3.ndim)

torch.Size([2, 2]) 2
torch.Size([1, 4]) 2
torch.Size([1, 1, 4]) 3


In [119]:
# 차원 축소
tt1 = t1.squeeze()
tt2 = t2.squeeze()
tt3 = t3.squeeze() # 1차원 모두 제거
tt4 = t3.squeeze(dim = 0) # 0번째 1차원만 제거 # dim = [0,1] : 0번째, 1번째 1차원 제거

# 1차원인 값만 축소 됨
print(tt1.shape, tt1.ndim) # 여전히 2차원
print(tt2.shape, tt2.ndim) # 2차원 -> 1차원
print(tt3.shape, tt3.ndim) # 3차원 -> 1차원
print(tt4.shape, tt4.ndim) # 3차원 -> 1차원

torch.Size([2, 2]) 2
torch.Size([4]) 1
torch.Size([4]) 1
torch.Size([1, 4]) 2


In [120]:
# 원소/요소 수 변경 없이 1차원 추가 => unsqueeze()
print(t1.shape, t1.ndim)

torch.Size([2, 2]) 2


In [121]:
tt1 = t1.unsqueeze(dim = 0) # 0번째 자리에 1차원 추가
tt2 = t1.unsqueeze(dim = 1) # 1번째 자리에 1차원 추가
tt3 = t1.unsqueeze(dim =-1) # 마지막 자리에 1차원 추가
print(tt1.shape, tt1.ndim)
print(tt2.shape, tt2.ndim)
print(tt3.shape, tt3.ndim)

torch.Size([1, 2, 2]) 3
torch.Size([2, 1, 2]) 3
torch.Size([2, 2, 1]) 3


Tensor 차원/형태 변경
- 메타 데이터가 변경

In [122]:
t1 = torch.tensor([[[1,2],[11,22],[44,55]]]) # 3행 2열 짜리가 한장
print(t1.shape, t1.ndim)
# dim 0 1 2
#     1 3 2

torch.Size([1, 3, 2]) 3


In [123]:
# 2개의 차원을 변경하는 메서드 : transpose() - 2개만 변경 가능
t11 = t1.transpose(0,2) # 0번 자리를 2번자리로 바꿔줘  # 3행 1열 짜리가 두장
print(t11.shape, t11.ndim)

torch.Size([2, 3, 1]) 3


In [124]:
# 2개의 차원을 변경하는 메서드 
t22 = t1.permute(1,2,0)  # 2행 1열이 세장
print(t22.shape, t22.ndim)

torch.Size([3, 2, 1]) 3
