### 이미지 데이터 분류
- 데이터 : sklearn.datasets의 MNIST ==> 디지털 숫자 0 ~ 9 손글씨 데이터셋
- 피쳐 : 이미지 픽셀 수, 28 * 28 = 784
- 타겟 : 0 ~ 9, 총 10개
- 학습유형 : 지도학습 + 분류

[1] 모듈 로딩 및 데이터 준비 <hr>

In [3]:
# 모듈 로딩
from sklearn.datasets import fetch_openml

In [14]:
# 데이터 로딩
mnist = fetch_openml('mnist_784',parser='auto') # 번치 타입

In [15]:
mnist.data.shape , mnist.target.shape

((70000, 784), (70000,))

In [16]:
mnist.data.describe()

pixel1   pixel2   pixel3   pixel4   pixel5   pixel6   pixel7   pixel8  \
count  70000.0  70000.0  70000.0  70000.0  70000.0  70000.0  70000.0  70000.0   
mean       0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
std        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
25%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
50%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
75%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
max        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel9  pixel10  ...      pixel775      pixel776      pixel777  \
count  70000.0  70000.0  ...  70000.000000  70000.000000  70000.000000   
mean       0.0      0.0  ...      0.197414      0.099543      0.046629   
std        0.0      0.0  ...      5.991206      4.256304      2.783732   
min        0.0      0.0  ...      0.000000      0.000000      0.000000   
25%        0.0      0.0  ...      0.000000      0.000000      0.000000   
50%        0.0      0.0  ...      0.000000      0.000000      0.000000   
75%        0.0      0.0  ...      0.000000      0.000000      0.000000   
max        0.0      0.0  ...    254.000000    254.000000    253.000000   

           pixel778      pixel779      pixel780  pixel781  pixel782  pixel783  \
count  70000.000000  70000.000000  70000.000000   70000.0   70000.0   70000.0   
mean       0.016614      0.012957      0.001714       0.0       0.0       0.0   
std        1.561822      1.553796      0.320889       0.0       0.0       0.0   
min        0.000000      0.000000      0.000000       0.0       0.0       0.0   
25%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
50%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
75%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
max      253.000000    254.000000     62.000000       0.0       0.0       0.0   

       pixel784  
count   70000.0  
mean        0.0  
std         0.0  
min         0.0  
25%         0.0  
50%         0.0  
75%         0.0  
max         0.0  

[8 rows x 784 columns]

[2] 데이터 전처리 <hr>
- 이미지 픽셀값 0~1로 스케일링
- MinMax써도 됨

In [25]:
featureDF = mnist.data
featureDF = featureDF / 255 # 최대값으로 나눈 것
featureDF.describe()

pixel1   pixel2   pixel3   pixel4   pixel5   pixel6   pixel7   pixel8  \
count  70000.0  70000.0  70000.0  70000.0  70000.0  70000.0  70000.0  70000.0   
mean       0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
std        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
25%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
50%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
75%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
max        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel9  pixel10  ...      pixel775      pixel776      pixel777  \
count  70000.0  70000.0  ...  70000.000000  70000.000000  70000.000000   
mean       0.0      0.0  ...      0.000774      0.000390      0.000183   
std        0.0      0.0  ...      0.023495      0.016691      0.010917   
min        0.0      0.0  ...      0.000000      0.000000      0.000000   
25%        0.0      0.0  ...      0.000000      0.000000      0.000000   
50%        0.0      0.0  ...      0.000000      0.000000      0.000000   
75%        0.0      0.0  ...      0.000000      0.000000      0.000000   
max        0.0      0.0  ...      0.996078      0.996078      0.992157   

           pixel778      pixel779      pixel780  pixel781  pixel782  pixel783  \
count  70000.000000  70000.000000  70000.000000   70000.0   70000.0   70000.0   
mean       0.000065      0.000051      0.000007       0.0       0.0       0.0   
std        0.006125      0.006093      0.001258       0.0       0.0       0.0   
min        0.000000      0.000000      0.000000       0.0       0.0       0.0   
25%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
50%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
75%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
max        0.992157      0.996078      0.243137       0.0       0.0       0.0   

       pixel784  
count   70000.0  
mean        0.0  
std         0.0  
min         0.0  
25%         0.0  
50%         0.0  
75%         0.0  
max         0.0  

[8 rows x 784 columns]

In [ ]:
targetSR = mnist.target

In [29]:
targetSR.unique()  # 문자열  

array([5, 0, 4, 1, 9, 2, 3, 6, 7, 8])

In [28]:
targetSR = targetSR.astype('int')

[3] 기계학습용 데이터셋 준비 <hr>
- 학습용, 검증용, 테스트용 3개 데이터셋 준비

In [30]:
# 모듈 로딩
from sklearn.model_selection import train_test_split

In [69]:
# 학습용 & 테스트용 분리 => MNIST database에서 제공한 6만개와 만개
xtrain,xtest,ytrain,ytest = featureDF.iloc[:60000], featureDF.iloc[60000:], targetSR[:60000], targetSR[60000:]

xtrain.shape,xtest.shape

((60000, 784), (10000, 784))

In [70]:
# 학습용 & 검증용 분리 => 학습용 데이터셋에서 일부를 검증용으로 준비
# 검증용 : 학습 시 모델 최적화가 잘 되는지 검사하는 데이터셋
# 테스트용 데이터 스코어가 높아야함. 검증용엔 중간에 평가할 때 사용
# 검증용 데이터는 매번 바뀌는게 좋음
xtrain,xval,ytrain,yval = train_test_split(xtrain,ytrain,
                                           test_size=0.3,
                                           stratify=ytrain,
                                           random_state=5)
xtrain.shape,xval.shape

((42000, 784), (18000, 784))

[4] 학습진행 <hr>

[4-1] 분류 방법 : : LogisticRegression

In [40]:
from sklearn.linear_model import LogisticRegression, SGDClassifier

In [71]:
lr_model = LogisticRegression(max_iter=3000)
lr_model.fit(xtrain,ytrain)

LogisticRegression(max_iter=3000)

In [72]:
train_score = lr_model.score(xtrain,ytrain)
val_score = lr_model.score(xval,yval)

train_score, val_score

(0.9429285714285714, 0.9173888888888889)

In [73]:
lr_model.n_iter_ 

array([721])

In [81]:
train_score = lr_model.score(xtrain,ytrain)
val_score = lr_model.score(xval,yval)
test_score = lr_model.score(xtest,ytest)

train_score, val_score, test_score

(0.9429285714285714, 0.9173888888888889, 0.9238)

[4-2] 확률적 경사하강법 기반 학습 <hr>
- 대량의 데이터를 학습 시 랜덤으로 데이터셋 1개 추출해서 학습 진행 => 최적화
- 장점 : 속도가 빨라짐
- 단점 : 정확도 떨어짐
- 개선 : 일정 데이터를 묶어서 학습 후 최적화 진행 => 미니배치 기법  # defalt : 32개 / 몇개로 묶어야 잘나올지 고민 -> 하이퍼 파라미터
- 학습모델 선정 필요

In [83]:
# 모듈 로딩 SGDClassifier => 분류 알고리즘을 SGD방법으로 학습 진행
# from sklearn.metrics import 
from sklearn.linear_model import SGDClassifier

In [85]:
# LogisticRegression 알고리즘으로 학습 진행
lr_sgd = SGDClassifier(loss = 'log_loss', random_state=5)
lr_sgd.fit(xtrain,ytrain)

SGDClassifier(loss='log_loss', random_state=5)

In [92]:
# 모델 파라미터 확인
print('n_iter :', lr_sgd.n_iter_)
print(f'[BEFORE] lr_sgd.coef_ :\n{lr_sgd.coef_}')
print(f'[BEFORE] lr_sgd.intercept_ :\n{lr_sgd.intercept_}')

n_iter : 24
[BEFORE] lr_sgd.coef_ :
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[BEFORE] lr_sgd.intercept_ :
[-7.97799393 -0.99830779 -2.94178586 -4.36810167 -2.2825444   0.13435885
 -4.56454107 -0.85661241 -7.83566869 -4.44152253]


In [94]:
lr_sgd.score(xtrain,ytrain), lr_sgd.score(xval,yval),lr_sgd.score(xtest,ytest)

(0.9238809523809524, 0.9167222222222222, 0.9165)

In [93]:
# 추가된 데이터에 대한 추가 학습 진행 => 기존 학습으로 최적화 된 상태 유지
import numpy as np

lr_sgd.partial_fit(xval,yval,np.unique(yval))

SGDClassifier(loss='log_loss', random_state=5)

[5] 학습 모델 성능 평가<hr>

In [76]:
## 분류 모델 성능평가 => accuracy, precision, recall, f1-score ==> classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay, classification_report

# 데이터가 불균형하면 정확도로 모델 성능 평가 파악 불가

In [80]:
# 클래스 비율
ytrain.value_counts(),yval.value_counts(),ytest.value_counts()  # 클래스 비율이 균형적 => 정확도로 모델 성능 평가 가능

(class
 1    4719
 7    4385
 3    4292
 2    4171
 9    4164
 0    4146
 6    4143
 8    4096
 4    4089
 5    3795
 Name: count, dtype: int64,
 class
 1    2023
 7    1880
 3    1839
 2    1787
 9    1785
 0    1777
 6    1775
 8    1755
 4    1753
 5    1626
 Name: count, dtype: int64,
 class
 1    1135
 2    1032
 7    1028
 3    1010
 9    1009
 4     982
 0     980
 8     974
 6     958
 5     892
 Name: count, dtype: int64)