1. 스칼라
2. 1차원이다
3. float16(half) - 데이터 크기 작다, float32, float64(double) - 데이터 크기 크다


In [1]:
import torch

In [61]:
#4
t1 = torch.tensor([10,-5,1.4,7,0,-1,0], dtype=torch.bool)
print(t1.dtype, t1.ndim,t1.data, t1.shape, t1.device, t1.requires_grad)

torch.bool 1 tensor([ True,  True,  True,  True, False,  True, False]) torch.Size([7]) cpu False


In [66]:
#5
t2 = torch.zeros(10,1)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [10]:
#6
t3 = torch.eye(5)

In [88]:
#7
t4 = torch.full_like(t3,3)

In [89]:
# 7 정답
t4_an = torch.eye(5) * 3
t4_an

tensor([[3., 0., 0., 0., 0.],
        [0., 3., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 3., 0.],
        [0., 0., 0., 0., 3.]])

In [93]:
#8
import numpy as np
data = np.arange(0,100,7)
t5 = torch.as_tensor(data, dtype = torch.float32)

[ 0  7 14 21 28 35 42 49 56 63 70 77 84 91 98]


In [91]:
#9
file = 'flower.jpg'
img = torch.randint( low=0, high=255, size=(80,120), dtype=torch.uint8 )

In [20]:
# 10
data = torch.rand(10)
t6 = torch.as_tensor(data)
t7 = t6.unsqueeze()
t8 = t6.transpose(0,1)
t9 = t6.permute() # 차원 변경

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [52]:
# 11
# 11 - 1
# t10 = {'국어':[90,70,80],'영어':[70,100,80],'수학':[99,88,77]}
t10 = torch.tensor([[90,70,80],[70,100,80],[99,88,77]])
# 11 - 2
print(torch.sum(t10,dim=1),t10.max(dim = 1)[0])
# 11 - 3
print(torch.sum(t10,dim=0),t10.max(dim = 0)[0])

tensor([240, 250, 264]) tensor([ 90, 100,  99])
tensor([259, 258, 237]) tensor([ 99, 100,  80])


In [71]:
# 12
# 12 - 1
data1 = torch.tensor([[90,70,80],[70,100,80],[99,88,77]])
data2 = torch.tensor([[0.5],[0.2],[0.7]])
# 12 - 2
# sum = torch.sum(data1,data2)
sub = data1.sub(data2)
mul = data1.mul(data2)
div = data1.div(data2)
# 12 - 3
matmul = data1.matmul(data2)

RuntimeError: expected m1 and m2 to have the same dtype, but got: __int64 != float

In [74]:
data1 = torch.tensor([[90,70,80],[70,100,80],[99,88,77]])
data2 = torch.tensor([[5],[2],[7]])
matmul = data1.matmul(data2)